### ISSUE TITLE
Error: Cannot find module 'coffee-script'

### ISSUE THREAD

**Issue by paolooo** [mikesmullin/borg-sample-project#1]
I'm sure I have coffee-script installed globally.

```
➜  borg-sample-project git:(master) ✗ node -v
v0.10.35
➜  borg-sample-project git:(master) ✗ coffee -v
CoffeeScript version 1.8.0
➜  borg-sample-project git:(master) ✗ borg assimilate aws-or-dev-web01.example.org --locals="ssh:host:'127.0.0.1',user:'',pass:''"
WARNING: File `./secret` missing or unreadable. @encrypt()/@decrypt() will not modify input.

167ms [info] importing /private/tmp/borg-sample-project/scripts/vendor/resources...
Error: Cannot find module 'coffee-script'
  at Function.Module._resolveFilename (module.js:338:15)
  at Function.Module._load (module.js:280:25)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/private/tmp/borg-sample-project/scripts/vendor/resources/template_renderer.coffee:1:16)
  at Object.<anonymous> (/private/tmp/borg-sample-project/scripts/vendor/resources/template_renderer.coffee:1:1)
  at Module._compile (module.js:456:26)
  at Object.loadFile (/Users/paowee/.nvm/v0.10.35/lib/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/Users/paowee/.nvm/v0.10.35/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/private/tmp/borg-sample-project/scripts/vendor/resources/index.coffee:4:20)
  at Object.<anonymous> (/private/tmp/borg-sample-project/scripts/vendor/resources/index.coffee:1:1)
  at Module._compile (module.js:456:26)
  at Object.loadFile (/Users/paowee/.nvm/v0.10.35/lib/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/Users/paowee/.nvm/v0.10.35/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Borg.module.exports.Borg.import (/Users/paowee/.nvm/v0.10.35/lib/node_modules/borg/src/index.coffee:371:8)
  at /Users/paowee/.nvm/v0.10.35/lib/node_modules/borg/src/index.coffee:469:7
  at Borg.module.exports.Borg.getServerObject (/Users/paowee/.nvm/v0.10.35/lib/node_modules/borg/src/index.coffee:324:14)
  at Borg.module.exports.Borg.assimilate (/Users/paowee/.nvm/v0.10.35/lib/node_modules/borg/src/index.coffee:465:6)
  at delegate_borg (/Users/paowee/.nvm/v0.10.35/lib/node_modules/borg/src/cli.coffee:213:3)
  at Object.<anonymous> (/Users/paowee/.nvm/v0.10.35/lib/node_modules/borg/src/cli.coffee:325:5)
  at Object.<anonymous> (/Users/paowee/.nvm/v0.10.35/lib/node_modules/borg/src/cli.coffee:1:1)
  at Module._compile (module.js:456:26)
  at Object.loadFile (/Users/paowee/.nvm/v0.10.35/lib/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
  at Module.load (/Users/paowee/.nvm/v0.10.35/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:312:12)
  at Module.require (module.js:364:17)
  at require (module.js:380:17)
  at Object.<anonymous> (/private/tmp/borg-sample-project/.cli.coffee:1:1)
  at Object.<anonymous> (/private/tmp/borg-sample-project/.cli.coffee:1:1)
  at Module._compile (module.js:456:26)
```

**Comment by mikesmullin** [comment]
this was the other dependency i thought was global. this one i am not sure about why it doesn't work for you but i know what i did that caused it, so i have reversed that. try now.

**Comment by paolooo** [comment]
Yeah! I even install `npm install coffee-script -g` manually. I know I have coffee-script installed globally. hmmmm... I'll try to figure it out why.

I have reinstalled borg already but it has still the same error. 

Will let you know.

**Comment by paolooo** [comment]
Eureka! I have to add this on my ~/.bashrc script

```
export NODE_PATH="$HOME/.nvm/v0.10.35/lib/node_modules"
$ source ~/.bashrc
```

because of this: ( https://github.com/borg-scripts/resources/blob/d06377c3ccb376a22f3994b885c6059f3436110e/template_renderer.coffee#L1 )

Thanks.

**Comment by mikesmullin** [comment]
interesting! i wonder why nvm did not add that for you? hmm... glad you were able to figure it out :)
